### PR TITLE
Compose Settings from multiple BaseSettings classes

### PR DESCRIPTION
**Pull request by uklft**
to approach this issue: https://github.com/miracum/ahd2fhir/blob/master/ahd2fhir/kafka_setup.py#L48

### CODE REVIEW

**Comment by chgl** [comment]
Brilliant, thank you so much. Looks much cleaner! I guess technically it's a breaking change though, since the external configuration needs to be changed (including the readme.md). But personally, I am all for it.

**Comment by chgl** [comment]
Could you also update the readme.md's section on Kafka with the new settings names as part of this PR? https://github.com/miracum/ahd2fhir#kafka-settings 

Other than that looks good to me.

**Comment by uklft** [comment]
Hey, glad that you like it! I'll update the README.

**Comment by uklft** [comment]
I noticed that pydantics `BaseSettings` supports only one level of prefix nesting ([see here](https://github.com/samuelcolvin/pydantic/issues/2232)). 
A fix would be to set the full prefix on the second-level objects:

~~~python
class KafkaProducerSettings(BaseSettings):
    compression_type: str = "gzip"

    class Config:
        env_prefix = "kafka_producer_"
~~~

**Comment by chgl** [comment]
Seems reasonable to me!

**Pull request merged**
